# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38962723cc8bc8e0c144027b4fabfcdb63521eada65a82b479c4e460a2902669199e03efe11370ff75d49dfd6dfdaa892f1d607530f682389e56134cc8fb6eec

test:
  secret_key_base: d66ae0ccd01fab71a1fc6b94afbad1dc99f02527351c3a2103a1d5207121ed6028400dd145cccb941432ecc8d411f881206e2811dfeb64651438bebd05c3d643

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
